name: Remove Audio

on:
  workflow_dispatch:
  

jobs:
  remove_audio:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:savoury1/ffmpeg4
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install demucs
          pip install gdown
          pip install --upgrade gdown

      - name: Create user folders
        run: mkdir -p $GITHUB_WORKSPACE/videos

      - name: Dowload video 
        run: gdown --folder ${{ secrets.LINK }} -O $GITHUB_WORKSPACE/videos

 
      - name: Run python script
        run: python remove_audio2.py
        
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos_without_music
          path: videos_without_music
