name: multi job Remove Audio

on:
  workflow_dispatch:

jobs:
  define-videos:
    runs-on: ubuntu-latest
    outputs:
      video_paths: ${{ steps.get-video-paths.outputs.video_paths }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install gdown
          pip install --upgrade gdown

      - name: Create videos folder
        run: mkdir -p $GITHUB_WORKSPACE/videos

      - name: Download videos
        run: gdown --folder ${{ secrets.LINK }} -O $GITHUB_WORKSPACE/videos

      - name: List downloaded videos
        id: get-video-paths
        run: |
          videos=$(ls $GITHUB_WORKSPACE/videos/*.mp4 | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "video_paths=$videos" >> $GITHUB_OUTPUT

  process-videos:
    needs: define-videos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        video_path: ${{ fromJSON(needs.define-videos.outputs.video_paths) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y ffmpeg
          pip install demucs

      - name: Create output folders
        run: |
          mkdir -p $GITHUB_WORKSPACE/demucs_output
          mkdir -p $GITHUB_WORKSPACE/videos_without_music

      - name: Run python script
        run: python remove_audio.py ${{ matrix.video_path }}

      - name: Archive processed video
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: processed_video_${{ matrix.video_path }}
          path: videos_without_music
